name: git push into hwonda repo for deploy to vercel

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HWON_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: "hwonda"
          destination-repository-name: "diki"
          user-email: ${{ secrets.HWON_EMAIL }}
          commit-message: ${{ github.event.commits[0].message || '[문서] 자정 자동 배포' }}
          target-branch: main
      - name: Trigger Vercel Deployment
        if: success() && github.event_name == 'schedule'
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
