name: deploy production to vercel

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    if: github.repository == 'dxwiki/diki'
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Install git
        run: apk add git

      - name: Force sync forked repo with upstream
        run: |
          git config --global user.name "hwonda"
          git config --global user.email "${{ secrets.HWON_EMAIL }}"
          git clone https://x-access-token:${{ secrets.HWON_TOKEN }}@github.com/hwonda/diki.git fork-repo
          cd fork-repo
          git remote add upstream https://github.com/dxwiki/diki.git
          git fetch upstream
          git checkout main
          git reset --hard upstream/main
          git push origin main --force

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HWON_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: "hwonda"
          destination-repository-name: "diki"
          user-email: ${{ secrets.HWON_EMAIL }}
          commit-message: ${{ github.event.commits[0].message || '[문서] 자정 자동 배포' }}
          target-branch: main

      - name: Trigger Vercel Deployment
        if: success() && github.event_name == 'schedule'
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
